[package]
name = "computational_art_and_design"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
opencv = "0.93.4"
rand = "0.8.5"
tokio = { version = "1", features = ["full"] }
num_cpus = "1.13"
rayon = "1.10.0"